#!/usr/bin/python3
"""Factorize as many numbers as possible into
a product of two smaller numbers"""

from sys import argv
from math import sqrt


def funct():
    """Function to search file to convert number and format"""

    try:
        revfile = sys.argv[1]
        with open(revfile) as f:
            for revnumber in f:
                revnumber = int(revnumber)
                print("{:d}=".format(revnumber), end="")
                if revnumber % 2 == 0:
                    print("{}={}*{}".format(revnumber, revnumber // 2))
                    continue
                tmp = int(sqrt(revnumber))
                if tmp % 2 == 0:
                    tmp += 1
                for i in range(3, tmp + 1, 2):
                    if revnumber % i == 0:
                        print("{}*{}".format(revnumber // i, i))
                        break
    except IndexError:
        pass


funct()
