#!/usr/bin/python3
"""Factorize as many numbers as possible into
a product of two smaller numbers"""

from sys import argv
from math import sqrt


def funct():
    """Function to search file to convert number and format"""

    try:
        with open(argv[1]) as f:
            for number in f:
                num = int(number)
                flag = 0
                for i in range(2, int(num / 2) + 1, 1):
                    if num % i == 0:
                        print("{:d}={}*{}".format(num, num // i, i))
                        flag = 1
                        break
                if flag == 0:
                    print("{:d}={}*{}".format(num, num, 1))
    except IndexError:
        pass


if __name__ == "__main__":
    funct()
