#!/usr/bin/python3
"""Factorize as many numbers as possible into
a product of two smaller numbers"""

from sys import argv
from fractions import gcd


def p_rho(n):
    """Function to search file to convert number and format"""
    x = 2
    y = 2
    d = 1
    f = lambda x: (x**2 + 1) % n
    while d == 1:
        x = f(x)
        y = f(f(y))
        d = gcd(abs(x - y), n)
    if d != n:
        return d


def read_file():
    try:
        with open(argv[1]) as f:
            for number in f:
                num = int(number)
                if num % 2 == 0:
                    print("{:d}={}*{}".format(num, num // 2, 2))
                else:
                    p = p_rho(num)
                    f1 = p
                    f2 = int(num / p)
                    print("{}={}*{}".format(num, f1, f2))
    except IndexError:
        pass


if __name__ == "__main__":
    read_file()
